version: "2.12.2"

services: 
  web: 
    tty: true
    build: 
        dockerfile: Dockerfile
        context: .
    command: bash -c "python manage.py runserver 127.0.0.1:8000"
    ports: 
      - 8000:8000
    restart: always