# Generated by Django 4.1.2 on 2022-12-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=800)),
                ('base_photo', models.ImageField(blank=True, upload_to='static/photos')),
            ],
        ),
        migrations.CreateModel(
            name='PlacePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='static/photos')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_APIs.place')),
            ],
        ),
    ]
